### ISSUE TITLE
leak Smtp server vulnerability

### ISSUE THREAD

**Issue by AhmdFahad** [ashrafablia1/gitintern#2]
# Secure your sensitive data

don`t ever push your sensitive data to public repo 
 _you could assign the data to environment variable or add it to .ignore_ 

### I was able to access your smtp server and send messages
![12](https://github.com/ashrafablia1/gitintern/assets/68047377/9ec46794-d2e1-4b8c-b368-831a18caf749)

![Sec](https://github.com/ashrafablia1/gitintern/assets/68047377/f7aa1025-b25a-4c54-a2de-6c8cd9f730c5)

**Comment by ashrafablia1** [comment]
I solved the problem. Thank you for the help
